Pin orbax-checkpoint version for Windows
Compatibility issue with a newer gpjax:
```
`uvloop` (v0.22.1) was included because `geometric-kernels:dev`
        (v0.4.2) depends on `gpjax` (v0.13.6) which depends on `flax`
        (v0.12.3) which depends on `orbax-checkpoint` (v0.11.33) which depends
        on `uvloop`
```
but
```
RuntimeError: uvloop does not support Windows at the moment
```